### ISSUE TITLE
login check fails

### ISSUE THREAD

**Issue by svancopp** [michaelarnauts/plugin.video.vtm.go#100]
using the plugin with Kodi 19.0 on OSMC 2019.07-1. When I check my login, I get following error:

2019-10-12 11:54:48.628 T:1544544992   ERROR: EXCEPTION: argument "buffer" for "write" must be a string or a bytearray
2019-10-12 11:54:48.630 T:1544544992   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: argument "buffer" for "write" must be a string or a bytearray
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.vtm.go/main.py", line 6, in <module>
                                                plugin.run(sys.argv)
                                              File "/home/osmc/.kodi/addons/plugin.video.vtm.go/resources/lib/plugin.py", line 1004, in run
                                                plugin.run(params)
                                              File "/home/osmc/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
                                                self._dispatch(self.path)
                                              File "/home/osmc/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
                                                view_func(**kwargs)
                                              File "/home/osmc/.kodi/addons/plugin.video.vtm.go/resources/lib/plugin.py", line 121, in check_credentials
                                                auth.get_token()
                                              File "/home/osmc/.kodi/addons/plugin.video.vtm.go/resources/lib/vtmgoauth.py", line 81, in get_token
                                                f.write(self._token)
                                            TypeError: argument "buffer" for "write" must be a string or a bytearray
                                            -->End of Python script error report<--

**Comment by michaelarnauts** [comment]
You are absolutely right. I will check this :)
