### ISSUE TITLE
Geoblocked content returns None and dumps trace

### ISSUE THREAD

**Issue by dagwieers** [michaelarnauts/plugin.video.vtm.go#65]
When testing from Travis, playing a Live TV stream causes a traceback that we should properly handle better. This test has now been disabled in Travis.
```
======================================================================
ERROR: test_play_livetv (test.test_routing.TestRouter)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/michaelarnauts/plugin.video.vtm.go/test/test_routing.py", line 97, in test_play_livetv
    plugin.run(['plugin://plugin.video.vtm.go/play/livetv/ea826456-6b19-4612-8969-864d1c818347?.pvr', '0', ''])
  File "/home/travis/build/michaelarnauts/plugin.video.vtm.go/resources/lib/plugin.py", line 699, in run
    plugin.run(params)
  File "/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/routing.py", line 130, in run
    self._dispatch(self.path)
  File "/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/routing.py", line 141, in _dispatch
    view_func(**kwargs)
  File "/home/travis/build/michaelarnauts/plugin.video.vtm.go/resources/lib/plugin.py", line 555, in play_livetv
    _stream('channels', channel)
  File "/home/travis/build/michaelarnauts/plugin.video.vtm.go/resources/lib/plugin.py", line 624, in _stream
    resolved_stream = _vtmgostream.get_stream(strtype, strid)
  File "/home/travis/build/michaelarnauts/plugin.video.vtm.go/resources/lib/vtmgostream.py", line 56, in get_stream
    anvato_info = self._extract_anvato_stream_from_stream_info(stream_info)
  File "/home/travis/build/michaelarnauts/plugin.video.vtm.go/resources/lib/vtmgostream.py", line 145, in _extract_anvato_stream_from_stream_info
    for stream in stream_info['video']['streams']:
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by mediaminister** [comment]
Geoblocked content should work in the EU when the user is authenticated, (the user account only needs a postal code, so this is less strict than with VRT NU)
The current implementation doesn't use the credentials at all, so playing geoblocked streams only works in Belgium.
First we need to fix EU roaming, maybe @michaelarnauts knows how the login api interacts with the anvato stream api.

**Comment by michaelarnauts** [comment]
You can get a json web token from the auth service. From what I remember, you need to add it in a `x-dpp-jwt` http header when making the calls to the vtm go service.

Code is already there: https://github.com/michaelarnauts/plugin.video.vtm.go/blob/master/resources/lib/vtmgo.py#L363

**Comment by mediaminister** [comment]
I found out VTM GO add-on used a deprecated api version that was geoblocked: https://github.com/michaelarnauts/plugin.video.vtm.go/pull/71

test_play_livetv works again on Travis. (worldwide)

**Comment by michaelarnauts** [comment]
It looks like #71 didn't fix the problem.

**Comment by mediaminister** [comment]
Strange, yesterday Travis didn't complain: https://github.com/michaelarnauts/plugin.video.vtm.go/runs/224784919

**Comment by michaelarnauts** [comment]
I've disabled the test again. I don't see why it worked yesterday, but it fails again now, with a newer api version.

https://github.com/michaelarnauts/plugin.video.vtm.go/runs/225443425
